version: "3.8"
services:
  ddev-lab-postgres:
    image: postgres:15.5-alpine
    platform: linux/x86_64
    container_name: ddev-lab-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    
networks:
  default:
    name: ddev-lab
    external: true